/**
 * FLASH Index Manager (FlashIndexManager)
 * High-performance In-Memory & Persistent Index Store for Blind Trapdoors and Range Buckets
 */

import { FlashBlindIndex } from '../crypto/blind_index.mjs';

export class FlashIndexManager {
  constructor() {
    // exactFieldName -> Map<trapdoorHash, Set<docId>>
    this.exactIndexes = new Map();
    // ngramFieldName -> Map<ngramHash, Set<docId>>
    this.ngramIndexes = new Map();
    // rangeFieldName -> Map<bucketHash, Set<docId>>
    this.rangeIndexes = new Map();
  }

  /**
   * Index document trapdoors
   * @param {string} docId
   * @param {object} blindPayload - Generated by client SDK
   */
  indexDocument(docId, blindPayload) {
    if (!blindPayload || typeof blindPayload !== 'object') return;

    // 1. Exact Trapdoors
    if (blindPayload.exact) {
      for (const [field, trapdoor] of Object.entries(blindPayload.exact)) {
        if (!this.exactIndexes.has(field)) {
          this.exactIndexes.set(field, new Map());
        }
        const fieldMap = this.exactIndexes.get(field);
        const trapKey = FlashBlindIndex.trapdoorKey(trapdoor);
        if (!fieldMap.has(trapKey)) {
          fieldMap.set(trapKey, new Set());
        }
        fieldMap.get(trapKey).add(docId);
      }
    }

    // 2. N-Gram Trapdoors (For Substring & Text matching)
    if (blindPayload.ngrams) {
      for (const [field, tokenList] of Object.entries(blindPayload.ngrams)) {
        if (!this.ngramIndexes.has(field)) {
          this.ngramIndexes.set(field, new Map());
        }
        const fieldMap = this.ngramIndexes.get(field);
        for (const token of tokenList) {
          const trapKey = FlashBlindIndex.trapdoorKey(token);
          if (!fieldMap.has(trapKey)) {
            fieldMap.set(trapKey, new Set());
          }
          fieldMap.get(trapKey).add(docId);
        }
      }
    }

    // 3. Range Buckets
    if (blindPayload.range) {
      for (const [field, rangeMeta] of Object.entries(blindPayload.range)) {
        if (!this.rangeIndexes.has(field)) {
          this.rangeIndexes.set(field, new Map());
        }
        const fieldMap = this.rangeIndexes.get(field);
        const trapKey = FlashBlindIndex.trapdoorKey(rangeMeta.token);
        if (!fieldMap.has(trapKey)) {
          fieldMap.set(trapKey, new Set());
        }
        fieldMap.get(trapKey).add(docId);
      }
    }
  }

  /**
   * Unindex document upon update or deletion
   * @param {string} docId
   */
  removeDocument(docId) {
    for (const fieldMap of this.exactIndexes.values()) {
      for (const set of fieldMap.values()) {
        set.delete(docId);
      }
    }
    for (const fieldMap of this.ngramIndexes.values()) {
      for (const set of fieldMap.values()) {
        set.delete(docId);
      }
    }
    for (const fieldMap of this.rangeIndexes.values()) {
      for (const set of fieldMap.values()) {
        set.delete(docId);
      }
    }
  }

  /**
   * Search by exact trapdoor
   * @param {string} field
   * @param {string} trapdoor
   * @returns {Set<string>}
   */
  findExact(field, trapdoor) {
    const fieldMap = this.exactIndexes.get(field);
    const trapKey = FlashBlindIndex.trapdoorKey(trapdoor);
    if (!fieldMap || !trapKey || !fieldMap.has(trapKey)) return new Set();
    return fieldMap.get(trapKey);
  }

  /**
   * Search by N-Gram tokens (Intersection of document sets for all query n-grams)
   * @param {string} field
   * @param {string[]} queryTokens
   * @returns {Set<string>}
   */
  findNGrams(field, queryTokens) {
    const fieldMap = this.ngramIndexes.get(field);
    if (!fieldMap || queryTokens.length === 0) return new Set();

    let candidateSet = null;

    for (const token of queryTokens) {
      const trapKey = FlashBlindIndex.trapdoorKey(token);
      const matchSet = fieldMap.get(trapKey);
      if (!matchSet || matchSet.size === 0) {
        return new Set(); // If any query ngram doesn't match, entire string won't match
      }

      if (candidateSet === null) {
        candidateSet = new Set(matchSet);
      } else {
        // Intersect
        const nextSet = new Set();
        for (const id of candidateSet) {
          if (matchSet.has(id)) nextSet.add(id);
        }
        candidateSet = nextSet;
        if (candidateSet.size === 0) break;
      }
    }

    return candidateSet || new Set();
  }

  /**
   * Search by Range Bucket tokens (Union of bucket matches)
   * @param {string} field
   * @param {string[]} rangeTokens
   * @returns {Set<string>}
   */
  findRangeBuckets(field, rangeTokens) {
    const fieldMap = this.rangeIndexes.get(field);
    if (!fieldMap || rangeTokens.length === 0) return new Set();

    const resultSet = new Set();
    for (const token of rangeTokens) {
      const trapKey = FlashBlindIndex.trapdoorKey(token);
      const bucketMatches = fieldMap.get(trapKey);
      if (bucketMatches) {
        for (const docId of bucketMatches) {
          resultSet.add(docId);
        }
      }
    }
    return resultSet;
  }
}
